version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:9-jdk-browsers
    steps:
      - checkout
      - run:
          name: Compile
          command: ./gradlew jar
      - store_artifacts:
          path: build/libs
          destination: dist

